<?php

declare(strict_types=1);

namespace Tests\Unit;

use App\Repositories\ClientRepository;
use App\Repositories\GalleryRepository;
use App\Repositories\UserRepository;
use Tests\Support\Factory;
use Tests\Support\TestCase;

/**
 * Two things are checked here: that hostile input is treated as data, and
 * that the source contains no string-built SQL for someone to regress into.
 */
final class SqlSafetyTest extends TestCase
{
    private const PAYLOADS = [
        "' OR '1'='1",
        "'; DROP TABLE clients; --",
        "admin'--",
        "1 UNION SELECT password_hash FROM users",
        "%' OR 1=1 --",
    ];

    public function testSearchTreatsInjectionAttemptsAsText(): void
    {
        Factory::client('Martin');
        Factory::client('Bernard');

        $clients = new ClientRepository();

        foreach (self::PAYLOADS as $payload) {
            $result = $clients->paginate(1, 25, $payload);

            $this->assertCount(0, $result['rows'], 'Injection payload matched rows: ' . $payload);
        }

        // The table is still there afterwards.
        $this->assertSame(2, $clients->count());
    }

    public function testLoginLookupTreatsInjectionAsText(): void
    {
        Factory::user('real@example.test', 'correct-horse-battery');
        $users = new UserRepository();

        foreach (self::PAYLOADS as $payload) {
            $this->assertNull($users->findByEmail($payload), 'Injection payload found a user: ' . $payload);
        }
    }

    public function testLikeWildcardsInASearchDoNotMatchEverything(): void
    {
        Factory::client('Durand');

        $clients = new ClientRepository();

        // A literal "%" must be searched for, not act as a wildcard.
        $this->assertCount(0, $clients->paginate(1, 25, '%')['rows']);
        $this->assertCount(0, $clients->paginate(1, 25, '_')['rows']);
        $this->assertCount(1, $clients->paginate(1, 25, 'Durand')['rows']);
    }

    public function testOrderByIsWhitelisted(): void
    {
        Factory::client('Alpha');
        Factory::client('Beta');

        $clients = new ClientRepository();

        // ORDER BY cannot be parameterised, so the column is matched against a
        // whitelist; an unknown value falls back to id instead of reaching SQL.
        $result = $clients->paginate(1, 25, '', 'id; DROP TABLE clients; --');

        $this->assertCount(2, $result['rows']);
        $this->assertSame(2, $clients->count());
    }

    public function testHostileTextRoundTripsUnchanged(): void
    {
        $payload = "Robert'); DROP TABLE clients; --";
        $clients = new ClientRepository();

        $id = $clients->insert([
            'first_name' => $payload,
            'last_name'  => 'Tables',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);

        $stored = $clients->find($id);

        $this->assertSame($payload, (string) $stored['first_name']);
        $this->assertSame(1, $clients->count());
    }

    public function testMassAssignmentIsLimitedToFillableColumns(): void
    {
        $users = new UserRepository();
        $user = Factory::user('fillable@example.test', 'correct-horse-battery');

        // `id` is not fillable; an attempt to change it must be dropped
        // rather than silently re-keying the row.
        $users->update((int) $user['id'], ['id' => 9999, 'name' => 'Changed']);

        $this->assertNotNull($users->find((int) $user['id']));
        $this->assertSame('Changed', (string) $users->find((int) $user['id'])['name']);
        $this->assertNull($users->find(9999));
    }

    /**
     * Only a reviewed set of fragments may be concatenated into SQL.
     *
     * The repositories do build SQL by concatenation — a WHERE clause assembled
     * from literal conditions, a table name from a class property, a generated
     * list of ":p0, :p1" placeholders. None of those carry caller input; the
     * values always arrive through bindings.
     *
     * This test freezes that: any NEW variable spliced into a query fails until
     * someone adds it here, which forces the question "where does this come
     * from?" to be answered in review rather than assumed.
     */
    public function testOnlyReviewedFragmentsAreConcatenatedIntoSql(): void
    {
        $allowed = [
            // Clauses assembled from literal strings inside the repository.
            'where', 'sql', 'sort', 'orderBy', 'assignments', 'conditions',
            // ":p0, :p1, …" generated by Repository::inPlaceholders().
            'placeholders',
            // Identifiers the class declares, never request data.
            'this->table',
            // Whitelisted by Repository::safeOrderBy() before it is spliced.
            'this->safeOrderBy',
        ];

        $offenders = [];

        foreach (glob(dirname(__DIR__, 2) . '/app/Repositories/*.php') ?: [] as $file) {
            foreach (file($file) ?: [] as $number => $line) {
                if (preg_match('/(SELECT|INSERT|UPDATE|DELETE|FROM|WHERE|VALUES|IN\s*\()/i', $line) !== 1) {
                    continue;
                }

                if (preg_match_all('/\.\s*\$([a-zA-Z_][a-zA-Z0-9_>\-]*)/', $line, $matches) === 0) {
                    continue;
                }

                foreach ($matches[1] as $variable) {
                    if (!in_array($variable, $allowed, true)) {
                        $offenders[] = sprintf('%s:%d $%s', basename($file), $number + 1, $variable);
                    }
                }
            }
        }

        $this->assertSame([], $offenders, "Unreviewed value spliced into SQL:\n" . implode("\n", $offenders));
    }

    public function testValuesNeverLandNextToAnOperatorByConcatenation(): void
    {
        // The shape an injection takes: a fragment ending in an operator or an
        // opening quote, followed by a concatenated variable.
        $offenders = [];

        foreach (glob(dirname(__DIR__, 2) . '/app/**/*.php') ?: [] as $file) {
            foreach (file($file) ?: [] as $number => $line) {
                // The line has to look like SQL before an operator on it means
                // anything: putenv($key . '=' . $value) is not a query.
                if (preg_match('/\b(SELECT|INSERT\s+INTO|UPDATE|DELETE\s+FROM|WHERE|VALUES)\b/i', $line) !== 1) {
                    continue;
                }

                if (preg_match('/(=|LIKE|VALUES\s*\(|,)\s*["\']\s*\.\s*\$/i', $line) === 1) {
                    $offenders[] = basename($file) . ':' . ($number + 1) . ' ' . trim($line);
                }
            }
        }

        $this->assertSame([], $offenders, "Value concatenated into SQL:\n" . implode("\n", $offenders));
    }

    public function testPdoUsesRealPreparedStatements(): void
    {
        $pdo = \App\Core\Database::connection();

        // With emulation on, PDO interpolates values client-side and the
        // database never sees a parameterised statement. Not every driver
        // exposes the attribute for reading — SQLite does not — so a driver
        // that cannot report it is accepted only because it never emulates.
        try {
            $emulated = $pdo->getAttribute(\PDO::ATTR_EMULATE_PREPARES);
            $this->assertFalse((bool) $emulated, 'Prepared statement emulation must stay off.');
        } catch (\PDOException) {
            $this->assertTrue(
                in_array($pdo->getAttribute(\PDO::ATTR_DRIVER_NAME), ['sqlite'], true),
                'A driver that hides ATTR_EMULATE_PREPARES must be one that never emulates.'
            );
        }

        $this->assertSame(\PDO::ERRMODE_EXCEPTION, $pdo->getAttribute(\PDO::ATTR_ERRMODE));
    }

    public function testUnpreparedQueryApiIsConfinedToInfrastructure(): void
    {
        $offenders = [];

        // query() and exec() take no bindings. They are legitimate only where
        // the statement is a literal: the migration runner and the connection
        // itself. Anywhere else is a review finding.
        foreach (['Controllers', 'Services', 'Repositories', 'Middleware'] as $directory) {
            foreach (glob(dirname(__DIR__, 2) . '/app/' . $directory . '/*.php') ?: [] as $file) {
                if (preg_match('/->(query|exec)\(/', (string) file_get_contents($file)) === 1) {
                    $offenders[] = $directory . '/' . basename($file);
                }
            }
        }

        $this->assertSame([], $offenders, 'Unprepared query in: ' . implode(', ', $offenders));
    }
}
